# Generated by Django 3.0.5 on 2023-06-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='intermediate_part_1_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='matric_marks',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
