# Generated by Django 3.0.5 on 2023-06-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20230610_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='intermediate_part_1_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='matric_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
